__name__ = 'NewUserBotV2'
__version__ = '0.0.2'
__author__ = 'flexyyyapk'
__link__ = 'https://t.me/d0br1u'
__gitHub__ = 'https://github.com/flexyyyapk/userbotmynew'
__news__ = '>✨Обновление 0.0.2\n>💡Что нового?\n> - Установка плагина, удаления плагина🎁\n> - Обновления скрипта🎃'
